name: Automerge2

on:
  push:
    branches:
    - release/**
    - main
  workflow_call:

jobs:
  automerge-branches:
    name: "Automerge branches"
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Merge to develop
        if: github.ref == 'refs/heads/main'
        run: |
          git checkout develop
          git merge origin/main
          git push origin develop

      - name: Merge to main and develop
        if: startsWith(github.ref, 'refs/heads/release/')
        run: |
          branch_name=$(git symbolic-ref --short HEAD)
          git checkout main
          git merge origin/$branch_name
          git push origin main

          git checkout develop
          git merge origin/$branch_name
          git push origin develop
