name: Build image

on:
  push:
    branches:
    - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      uses: cloudposse/github-action-docker-compose-test-run@main
      with:
        file: docker-compose.yaml
