name: Build image

on:
  push:
    branches:
    - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build
      run: docker-compose build
