name: Validate JSONs
on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited
      - reopened
    branches:
      - main
  
  workflow_dispatch:

jobs:
  validate_jsons:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate JSONs step
        run: |
          # Get the branch name from the event payload
          branch_name=$(jq -r '.pull_request.head.ref' "$GITHUB_EVENT_PATH")

          git fetch origin "$branch_name"
          git checkout "$branch_name"
          npm install -y ajv minimist
          echo "Listing the files:"
          json_files=$(gh pr diff $PR_NUMBER --name-only | grep -oiP '^(?!.github\/workflows\/.+\b).+\.json$')
          echo $json_files
          readarray -t files <<< $json_files
          for file in "${files[@]}"; do
            echo "Validating file '$file'..."
            error=""
            result=$(node .github/workflows/json-validator.js --schema=.github/workflows/schema.json --json=$file) || error=$result
            if [ ! -z "$error" ]; then
              echo "Error found in file '$file': $error"
              [ ! -f errors.txt ] && echo $'| File | Error validation message |\n|--------|--------|' >> errors.txt
              echo "| **$file** | \`$error\` |" >> errors.txt
            fi
          done
          [ -f errors.txt ] && echo "Uploading the review to the pull request..." && gh pr review $PR_NUMBER --request-changes --body-file errors.txt
          echo "All done!"
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
