name: Multiconditional

on:
  push:
    branches:
    - "*"

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build
      run: docker-compose build

  release:
    needs: build_image
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: LS
      run: ls
        
  notify_slack:
    needs: release
    runs-on: ubuntu-latest
    name: Notify Slack on Release
    steps:
    - name: LS
      run: ls
