name: Notify Slack on Release

on:
  release:
    types:
    - created

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    name: Build release notes message
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - run: |
        version=$(gh release view --json name --jq .name)
        echo "# :mega: The version $version has been released :mega:" >> releasenotes.md
        gh release view --json body --jq .body >> releasenotes.md
        cat releasenotes.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - run: |
        npm install slackify-markdown
        echo "const fs=require('fs'),slackifyMarkdown=require('slackify-markdown'),fileName=process.argv[2],markdown=fs.readFileSync(fileName,'utf-8');var result=slackifyMarkdown(markdown);console.log(result);" > converter.js
        echo "{\"text\":\"$(node converter.js releasenotes.md)\"}" | iconv > payload-slack-content.json
        cat payload-slack-content.json
        #slack_message=$(node converter.js releasenotes.md)

    - uses: slackapi/slack-github-action@v1.23.0
      with:
        payload-file-path: "./payload-slack-content.json"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
